modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "immersive_cinematics"
version = "${version}"
displayName = "ImmersiveCinematics"
authors = "sanzi"
description = '''
A cinematic camera mod designed for cutscenes and immersive storytelling. Allows detached camera control and tripod mode.
'''
#logoFile = ""

[[dependencies.immersive_cinematics]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_cinematics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_cinematics]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
