// ─────────────────────────────────────────────────────────────
// 离线演示数据：未连接游戏时自动加载，让编辑器界面完整可见
// Schema 与 Java 侧 MetaSchemas / TrackSchemas / TriggerSchemas 保持一致
// ─────────────────────────────────────────────────────────────

import type { Schema, ScriptDoc } from './types'

// ── 离线 Schema（与 Java 侧导出格式一致）──────────────────────

export const DEMO_SCHEMA: Schema = {
  meta: {
    id: { type: 'string', default: 'untitled', required: true, enumValues: [], section: 'info' },
    name: { type: 'string', default: 'Untitled', required: true, enumValues: [], section: 'info' },
    author: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
    version: { type: 'int', default: 3, required: true, enumValues: [], section: 'info' },
    description: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
    dimension: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
    block_keyboard: { type: 'bool', default: true, required: false, enumValues: [], section: 'runtime' },
    block_mouse: { type: 'bool', default: true, required: false, enumValues: [], section: 'runtime' },
    block_mob_ai: { type: 'bool', default: false, required: false, enumValues: [], section: 'runtime' },
    hide_hud: { type: 'bool', default: true, required: false, enumValues: [], section: 'runtime' },
    hide_arm: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    suppress_bob: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    suppress_distortion: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    hide_chat: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    hide_scoreboard: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    hide_action_bar: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    hide_title: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    hide_subtitles: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    hide_hotbar: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    hide_crosshair: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    hide_bossbar: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    hide_skip_hud: { type: 'bool', default: null, required: false, enumValues: [], section: 'runtime' },
    render_player_model: { type: 'bool', default: true, required: false, enumValues: [], section: 'runtime' },
    pause_when_game_paused: { type: 'bool', default: true, required: false, enumValues: [], section: 'runtime' },
    interruptible: { type: 'bool', default: true, required: false, enumValues: [], section: 'runtime' },
    skippable: { type: 'bool', default: true, required: false, enumValues: [], section: 'runtime' },
    hold_at_end: { type: 'bool', default: false, required: false, enumValues: [], section: 'runtime' },
    hud_layers: { type: 'object', default: null, required: false, enumValues: [], section: 'runtime' },
    priority: { type: 'int', default: 0, required: false, enumValues: [], section: 'runtime' },
    skip_vote_ratio: { type: 'int', default: null, required: false, enumValues: [], section: 'runtime' },
    camera_mob_spawn: { type: 'bool', default: false, required: false, enumValues: [], section: 'camera' },
    camera_mob_radius: { type: 'int', default: 2, required: false, enumValues: [], section: 'camera' },
    camera_mob_ai: { type: 'bool', default: false, required: false, enumValues: [], section: 'camera' },
  },
  tracks: {
    CAMERA: {
      clips: {
        transition: { type: 'enum', default: 'cut', required: false, enumValues: ['cut', 'morph'], section: 'info' },
        transition_duration: { type: 'float', default: 0.5, required: false, enumValues: [], section: 'info' },
        interpolation: { type: 'enum', default: 'linear', required: false, enumValues: ['linear', 'smooth'], section: 'info' },
        curve: { type: 'bezier_curve', default: null, required: false, enumValues: [], section: 'info' },
        dimension: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
        loop: { type: 'bool', default: false, required: false, enumValues: [], section: 'info' },
        loop_count: { type: 'int', default: -1, required: false, enumValues: [], section: 'info' },
        loop_mode: { type: 'enum', default: 'repeat', required: false, enumValues: ['repeat', 'pingpong'], section: 'info' },
        cam_breath_enabled: { type: 'bool', default: false, required: false, enumValues: [], section: 'info' },
        cam_breath_intensity: { type: 'float', default: 0.05, required: false, enumValues: [], section: 'info' },
        cam_breath_seed: { type: 'int', default: 0, required: false, enumValues: [], section: 'info' },
        cam_breath_type: { type: 'enum', default: 'perlin', required: false, enumValues: ['perlin', 'perlin_axis', 'sine', 'trauma'], section: 'info' },
        cam_breath_speed: { type: 'float', default: 1.0, required: false, enumValues: [], section: 'info' },
        cam_breath_trauma: { type: 'float', default: 1.0, required: false, enumValues: [], section: 'info' },
        cam_breath_decay: { type: 'float', default: 0.5, required: false, enumValues: [], section: 'info' },
        orient: { type: 'enum', default: 'manual', required: false, enumValues: ['manual', 'tangent'], section: 'info' },
        yaw_offset: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        pitch_offset: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
      },
      keyframes: {
        position: { type: 'position', default: null, required: true, enumValues: [], section: 'info' },
        position_mode: { type: 'enum', default: 'relative', required: false, enumValues: ['relative', 'absolute'], section: 'info' },
        follow: { type: 'enum', default: 'none', required: false, enumValues: ['none', 'entity'], section: 'info' },
        follow_selector: { type: 'string', default: '@p', required: false, enumValues: [], section: 'info' },
        look_at: { type: 'enum', default: 'none', required: false, enumValues: ['none', 'coordinate', 'entity'], section: 'info' },
        look_at_selector: { type: 'string', default: '@p', required: false, enumValues: [], section: 'info' },
        look_at_target_x: { type: 'float', default: null, required: false, enumValues: [], section: 'info' },
        look_at_target_y: { type: 'float', default: null, required: false, enumValues: [], section: 'info' },
        look_at_target_z: { type: 'float', default: null, required: false, enumValues: [], section: 'info' },
        look_at_target_structure: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
        look_at_target: { type: 'map', default: null, required: false, enumValues: [], section: 'info' },
        yaw_base: { type: 'enum', default: 'world', required: false, enumValues: ['world', 'entity', 'line'], section: 'info' },
        pitch_base: { type: 'enum', default: 'world', required: false, enumValues: ['world', 'entity', 'line'], section: 'info' },
        yaw_base_selector: { type: 'string', default: '@p', required: false, enumValues: [], section: 'info' },
        yaw_base_from: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
        yaw_base_to: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
        yaw: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        pitch: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        roll: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        fov: { type: 'float', default: 70, required: false, enumValues: [], section: 'info' },
        zoom: { type: 'float', default: 1.0, required: false, enumValues: [], section: 'info' },
      },
    },
    LETTERBOX: {
      clips: {},
      keyframes: {
        aspect_ratio: { type: 'float', default: 2.35, required: false, enumValues: [], section: 'info' },
      },
    },
    AUDIO: {
      clips: {
        sound: { type: 'string', default: null, required: true, enumValues: [], section: 'info' },
        source: { type: 'enum', default: 'file', required: false, enumValues: ['file', 'minecraft'], section: 'info' },
        volume: { type: 'float', default: 1.0, required: false, enumValues: [], section: 'info' },
        pitch: { type: 'float', default: 1.0, required: false, enumValues: [], section: 'info' },
        loop: { type: 'bool', default: false, required: false, enumValues: [], section: 'info' },
        fade_in: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        fade_out: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        attenuation: { type: 'enum', default: 'linear', required: false, enumValues: ['none', 'linear', 'inverse'], section: 'info' },
        position_mode: { type: 'enum', default: 'relative', required: false, enumValues: ['relative', 'absolute'], section: 'info' },
        category: { type: 'enum', default: 'music', required: false, enumValues: ['music', 'ambient'], section: 'info' },
      },
      keyframes: {
        volume: { type: 'float', default: 1.0, required: false, enumValues: [], section: 'info' },
        x: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        y: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        z: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
      },
    },
    EVENT: {
      clips: {
        event_type: { type: 'string', default: 'command', required: false, enumValues: [], section: 'info' },
      },
      keyframes: {
        event_type: { type: 'string', default: 'command', required: false, enumValues: [], section: 'info' },
        command: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
        position: { type: 'map', default: null, required: false, enumValues: [], section: 'info' },
      },
    },
    MOD_EVENT: {
      clips: {
        event_type: { type: 'string', default: null, required: true, enumValues: [], section: 'info' },
        data: { type: 'map', default: null, required: false, enumValues: [], section: 'info' },
      },
      keyframes: {
        event_type: { type: 'string', default: 'mod_event', required: false, enumValues: [], section: 'info' },
        data: { type: 'map', default: null, required: false, enumValues: [], section: 'info' },
      },
    },
    OVERLAY: {
      clips: {
        layer_type: { type: 'enum', default: 'fade', required: true, enumValues: ['fade', 'image', 'subtitle', 'pip'], section: 'info' },
        color: { type: 'string', default: '#000000', required: false, enumValues: [], section: 'info' },
        path: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
        text: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
        z_index: { type: 'int', default: 20, required: false, enumValues: [], section: 'info' },
        interpolation: { type: 'enum', default: 'linear', required: false, enumValues: ['linear', 'smooth'], section: 'info' },
      },
      keyframes: {
        opacity: { type: 'float', default: 0.0, required: false, enumValues: [], section: 'info' },
        x: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        y: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        font_scale: { type: 'float', default: 1, required: false, enumValues: [], section: 'info' },
        scale_x: { type: 'float', default: 1, required: false, enumValues: [], section: 'info' },
        scale_y: { type: 'float', default: 1, required: false, enumValues: [], section: 'info' },
      },
    },
  },
  triggers: {
    types: ['login', 'location', 'advancement', 'biome', 'entity_kill', 'entity_interact', 'block_interact', 'item_on_interact', 'dimension_change', 'item_craft', 'item_use', 'item_consume', 'item_release', 'item_instant_use', 'item_use_interrupt', 'item_pickup', 'item_drop', 'xp', 'dimension', 'observation', 'inventory', 'structure', 'gamestage'],
    conditions: {
      login: {},
      location: {
        dimension: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
        position: { type: 'map', default: null, required: false, enumValues: [], section: 'info' },
        radius: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        corner1: { type: 'map', default: null, required: false, enumValues: [], section: 'info' },
        corner2: { type: 'map', default: null, required: false, enumValues: [], section: 'info' },
      },
      advancement: { advancement: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      biome: { biome: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      entity_kill: {
        entity: { type: 'string', default: null, required: true, enumValues: [], section: 'info' },
        mode: { type: 'enum', default: 'or', required: false, enumValues: ['or', 'and'], section: 'info' },
        dimension: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
        biome: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
        position: { type: 'map', default: null, required: false, enumValues: [], section: 'info' },
        radius: { type: 'float', default: 0, required: false, enumValues: [], section: 'info' },
        corner1: { type: 'map', default: null, required: false, enumValues: [], section: 'info' },
        corner2: { type: 'map', default: null, required: false, enumValues: [], section: 'info' },
      },
      entity_interact: { target: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      block_interact: { target: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      item_on_interact: {
        item: { type: 'string', default: null, required: true, enumValues: [], section: 'info' },
        target: { type: 'string', default: null, required: true, enumValues: [], section: 'info' },
        target_type: { type: 'enum', default: '', required: false, enumValues: ['', 'block', 'entity'], section: 'info' },
      },
      dimension_change: {
        dimension: { type: 'string', default: null, required: true, enumValues: [], section: 'info' },
        from_dimension: { type: 'string', default: '', required: false, enumValues: [], section: 'info' },
      },
      item_craft: { item: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      item_use: { item: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      item_consume: { item: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      item_release: { item: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      item_instant_use: { item: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      item_use_interrupt: { item: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      item_pickup: { item: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      item_drop: { item: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      xp: {
        level: { type: 'int', default: null, required: false, enumValues: [], section: 'info' },
        total: { type: 'int', default: null, required: false, enumValues: [], section: 'info' },
      },
      dimension: { dimension: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
      observation: {
        target: { type: 'string', default: null, required: true, enumValues: [], section: 'info' },
        target_type: { type: 'enum', default: '', required: false, enumValues: ['', 'block', 'entity'], section: 'info' },
        reach: { type: 'float', default: 4.5, required: false, enumValues: [], section: 'info' },
      },
      inventory: {
        items: { type: 'map', default: null, required: true, enumValues: [], section: 'info' },
        mode: { type: 'enum', default: 'and', required: false, enumValues: ['and', 'or'], section: 'info' },
        change: { type: 'enum', default: '', required: false, enumValues: ['', 'increase', 'decrease'], section: 'info' },
      },
      structure: {
        structure: { type: 'string', default: null, required: true, enumValues: [], section: 'info' },
        radius: { type: 'int', default: 0, required: false, enumValues: [], section: 'info' },
      },
      gamestage: { stage: { type: 'string', default: null, required: true, enumValues: [], section: 'info' } },
    },
  },
}

// ── 示例脚本 ──────────────────────────────────────────────────

export const DEMO_SCRIPT: ScriptDoc = {
  meta: {
    id: 'demo_cinematic',
    name: '演示过场动画',
    author: 'ImmersiveCinematics',
    version: 3,
    description: '离线演示脚本，展示编辑器各功能',
    dimension: '',
    block_keyboard: true,
    block_mouse: true,
    block_mob_ai: false,
    hide_hud: true,
    hide_arm: null,
    suppress_bob: null,
    suppress_distortion: null,
    hide_chat: null,
    hide_scoreboard: null,
    hide_action_bar: null,
    hide_title: null,
    hide_subtitles: null,
    hide_hotbar: null,
    hide_crosshair: null,
    hide_bossbar: null,
    hide_skip_hud: null,
    render_player_model: true,
    pause_when_game_paused: true,
    interruptible: true,
    skippable: true,
    hold_at_end: false,
    priority: 0,
    skip_vote_ratio: null,
    camera_mob_spawn: false,
    camera_mob_radius: 2,
    camera_mob_ai: false,
    triggers: [
      {
        id: 'trigger_1',
        type: 'location',
        conditions: {
          dimension: 'minecraft:overworld',
          position: { x: 0, y: 64, z: 0 },
          radius: 10,
        },
        repeatable: false,
        delay: 0,
      },
    ],
  },
  timeline: {
    total_duration: 15,
    tracks: [
      {
        type: 'CAMERA',
        id: 'camera_1',
        clips: [
          {
            start_time: 0,
            duration: 5,
            transition: 'cut',
            transition_duration: 0.5,
            interpolation: 'smooth',
            keyframes: [
              { time: 0, position: { dx: 0, dy: 2, dz: 0 }, position_mode: 'relative', yaw: 0, pitch: 0, roll: 0, fov: 70, zoom: 1.0 },
              { time: 2.5, position: { dx: 3, dy: 3, dz: -5 }, position_mode: 'relative', yaw: 45, pitch: -10, roll: 0, fov: 70, zoom: 1.0 },
              { time: 5, position: { dx: 5, dy: 2, dz: -10 }, position_mode: 'relative', yaw: 90, pitch: 0, roll: 0, fov: 60, zoom: 1.2 },
            ],
          },
          {
            start_time: 5,
            duration: 5,
            transition: 'morph',
            transition_duration: 1.0,
            interpolation: 'linear',
            keyframes: [
              { time: 0, position: { dx: 5, dy: 2, dz: -10 }, position_mode: 'relative', yaw: 90, pitch: 0, roll: 0, fov: 60, zoom: 1.2 },
              { time: 5, position: { dx: 10, dy: 5, dz: -15 }, position_mode: 'relative', yaw: 180, pitch: 15, roll: 5, fov: 70, zoom: 1.0 },
            ],
          },
          {
            start_time: 10,
            duration: 5,
            transition: 'cut',
            transition_duration: 0.5,
            interpolation: 'smooth',
            cam_breath_enabled: true,
            cam_breath_type: 'perlin',
            cam_breath_intensity: 0.08,
            cam_breath_speed: 1.5,
            keyframes: [
              { time: 0, position: { dx: 10, dy: 5, dz: -15 }, position_mode: 'relative', yaw: 180, pitch: 15, roll: 5, fov: 70, zoom: 1.0 },
              { time: 5, position: { dx: 10, dy: 8, dz: -20 }, position_mode: 'relative', look_at: 'coordinate', look_at_target_x: 0, look_at_target_y: 64, look_at_target_z: 0, yaw: 0, pitch: -5, roll: 0, fov: 50, zoom: 1.5 },
            ],
          },
        ],
      },
      {
        type: 'AUDIO',
        id: 'audio_1',
        clips: [
          {
            start_time: 0,
            duration: 10,
            sound: 'music/demo_bgm.ogg',
            source: 'file',
            volume: 1.0,
            pitch: 1.0,
            fade_in: 1.0,
            fade_out: 2.0,
            category: 'music',
            keyframes: [
              { time: 0, volume: 0.0 },
              { time: 1, volume: 1.0 },
              { time: 8, volume: 1.0 },
              { time: 10, volume: 0.0 },
            ],
          },
        ],
      },
      {
        type: 'OVERLAY',
        id: 'overlay_1',
        clips: [
          {
            start_time: 0,
            duration: 3,
            layer_type: 'fade',
            color: '#000000',
            z_index: 20,
            keyframes: [
              { time: 0, opacity: 1.0 },
              { time: 1.5, opacity: 0.0 },
              { time: 3, opacity: 0.0 },
            ],
          },
          {
            start_time: 12,
            duration: 3,
            layer_type: 'subtitle',
            text: '演示结束',
            z_index: 30,
            font_scale: 1.5,
            keyframes: [
              { time: 0, opacity: 0.0 },
              { time: 0.5, opacity: 1.0 },
              { time: 2.5, opacity: 1.0 },
              { time: 3, opacity: 0.0 },
            ],
          },
        ],
      },
      {
        type: 'LETTERBOX',
        id: 'letterbox_1',
        clips: [
          {
            start_time: 1,
            duration: 13,
            keyframes: [
              { time: 0, aspect_ratio: 16 / 9 },
              { time: 1, aspect_ratio: 2.35 },
              { time: 12, aspect_ratio: 2.35 },
              { time: 13, aspect_ratio: 16 / 9 },
            ],
          },
        ],
      },
      {
        type: 'EVENT',
        id: 'event_1',
        clips: [
          {
            start_time: 5,
            duration: 0.1,
            event_type: 'command',
            keyframes: [
              { time: 0, event_type: 'command', command: 'title @a title {"text":"第二章"}' },
            ],
          },
          {
            start_time: 10,
            duration: 0.1,
            event_type: 'command',
            keyframes: [
              { time: 0, event_type: 'command', command: 'playsound minecraft:block.note_block.pling master @a' },
            ],
          },
        ],
      },
    ],
  },
}
